print("--WELCOME TO TIME CONVERTER--")
print("[1] Seconds")
print("[2] Minutes")
print("[3] Hours")
print("[4] Days")
print("[5] Weeks")
print("[6] Months")
print("[7] Years")
print("[8] EXIT")

user_choice = input("Enter your choice above: ")
while user_choice in ["1", "2", "3", "4", "5", "6", "7"]:
        if user_choice == "1":
            seconds = int(input("Enter the number of seconds: "))
            print("[Seconds]:", seconds)
            print("[Minutes]:", seconds // 60)
            print("[Hours]:", seconds // 3600)
            print("[Days]:", seconds // 86400)
            print("[Weeks]:", seconds // 604800)
            print("[Months]:", seconds // 2629746)
            print("[Years]:", seconds // 31556952)
        elif user_choice == "2":
            minutes = int(input("Enter the number of minutes: "))
            print("[Seconds]:", minutes * 60)
            print("[Minutes]:", minutes)
            print("[Hours]:", minutes // 60)
            print("[Days]:", minutes // 1440)
            print("[Weeks]:", minutes // 10080)
            print("[Months]:", minutes * 2.2816E-5)
            print("[Years]:", minutes * 1.9013E-6)
        elif user_choice == "3":
            hours = int(input("Enter the number of hours: "))
            print("[Seconds]:", hours * 3600)
            print("[Minutes]:", hours * 60)
            print("[Hours]:", hours)
            print("[Days]:", hours // 24)
            print("[Weeks]:", hours // 168)
            print("[Months]:", hours * 0.001369)
            print("[Years]:", hours * 0.000114)
        elif user_choice == "4":
            days = int(input("Enter the number of days: "))
            print("[Seconds]:", days * 86400)
            print("[Minutes]:", days * 1440)
            print("[Hours]:", days * 24)
            print("[Days]:", days)
            print("[Weeks]:", days // 7)
            print("[Months]:", days // 0.032855)
            print("[Years]:", days // 0.002738)
        elif user_choice == "5":
            weeks = int(input("Enter the number of weeks: "))
            print("[Seconds]:", weeks * 604800)
            print("[Minutes]:", weeks * 10080)
            print("[Hours]:", weeks * 168)
            print("[Days]:", weeks * 7)
            print("[Weeks]:", weeks)
            print("[Months]:", weeks * 0.229984)
            print("[Years]:", weeks * 0.019165)
        elif user_choice == "6":
            months = int(input("Enter the number of months: "))
            print("[Seconds]:", months * 2629746)
            print("[Minutes]:", months * 43829.1)
            print("[Hours]:", months * 730.485)
            print("[Days]:", months * 30.436875)
            print("[Weeks]:", months * 4.348125)
            print("[Months]:", months)
            print("[Years]:", months // 12)
        else:
            years = int(input("Enter the number of years: "))
        
